# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class HanaProvisioningStatesEnum(Enum):

    accepted = "Accepted"
    creating = "Creating"
    updating = "Updating"
    failed = "Failed"
    succeeded = "Succeeded"
    deleting = "Deleting"
    migrating = "Migrating"
