# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .hana_management_client import HanaManagementClient
from .version import VERSION

__all__ = ['HanaManagementClient']

__version__ = VERSION

