# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import ServiceClient
from msrest import Serializer, Deserializer
from msrestazure import AzureConfiguration
from .version import VERSION
from .operations.sap_monitors_operations import SapMonitorsOperations
from .operations.provider_instances_operations import ProviderInstancesOperations
from . import models


class HanaManagementClientConfiguration(AzureConfiguration):
    """Configuration for HanaManagementClient
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param subscription_id: Subscription ID which uniquely identify Microsoft
     Azure subscription. The subscription ID forms part of the URI for every
     service call.
    :type subscription_id: str
    :param str base_url: Service URL
    """

    def __init__(
            self, credentials, subscription_id, base_url=None):

        if credentials is None:
            raise ValueError("Parameter 'credentials' must not be None.")
        if subscription_id is None:
            raise ValueError("Parameter 'subscription_id' must not be None.")
        if not isinstance(subscription_id, str):
            raise TypeError("Parameter 'subscription_id' must be str.")
        if not base_url:
            base_url = 'https://management.azure.com'

        super(HanaManagementClientConfiguration, self).__init__(base_url)

        self.add_user_agent('azure.mgmt.saphanaonazure/{}'.format(VERSION))
        self.add_user_agent('Azure-SDK-For-Python')

        self.credentials = credentials
        self.subscription_id = subscription_id


class HanaManagementClient(object):
    """The SAP HANA on Azure Management Client.

    :ivar config: Configuration for client.
    :vartype config: HanaManagementClientConfiguration

    :ivar sap_monitors: SapMonitors operations
    :vartype sap_monitors: azure.mgmt.saphanaonazure.operations.SapMonitorsOperations
    :ivar provider_instances: ProviderInstances operations
    :vartype provider_instances: azure.mgmt.saphanaonazure.operations.ProviderInstancesOperations

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param subscription_id: Subscription ID which uniquely identify Microsoft
     Azure subscription. The subscription ID forms part of the URI for every
     service call.
    :type subscription_id: str
    :param str base_url: Service URL
    """

    def __init__(
            self, credentials, subscription_id, base_url=None):

        self.config = HanaManagementClientConfiguration(credentials, subscription_id, base_url)
        self._client = ServiceClient(self.config.credentials, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2020-02-07-preview'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.sap_monitors = SapMonitorsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.provider_instances = ProviderInstancesOperations(
            self._client, self.config, self._serialize, self._deserialize)
